[tool.black]
exclude = '''
(
    (^|/)\.
    | inorbit_edge/inorbit_pb2.py
)
'''

[tool.coverage.run]
source = ["inorbit_edge"]

[tool.flake8]
exclude = [".*/", "build/", "inorbit_edge/inorbit_pb2.py"]
max-line-length = 88
show-source = true
statistics = true
