[tool.black]
exclude = '''
(
    (^|/)\.
    | inorbit_edge/inorbit_pb2.py
)
'''

[tool.bump2version]
commit = true
current_version = "1.13.0"
tag = true

[[tool.bump2version.file_pattern]]
filename = "setup.py"
replace = "VERSION=\"{new_version}\""
search = "VERSION=\"{current_version}\""

[[tool.bump2version.file_pattern]]
filename = "inorbit_edge/__init__.py"
replace = "__version__=\"{new_version}\""
search = "__version__=\"{current_version}\""

[tool.coverage.run]
source = ["inorbit_edge"]

[tool.flake8]
exclude = [".*/", "build/", "inorbit_edge/inorbit_pb2.py"]
max-line-length = 88
show-source = true
statistics = true
